[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
billboard_market = "79Za2f2rCStCvfTv74JPhDBS9BEW48mx9gNXaLvgFRdt"

[programs.devnet]
billboard_market = "79Za2f2rCStCvfTv74JPhDBS9BEW48mx9gNXaLvgFRdt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yatharthjain/RENTOEARN/keys/devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
