providers = []

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install -g pnpm && pnpm install --no-frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd apps/web && pnpm prisma generate && pnpm prisma db push && pnpm build"]

[start]
cmd = "cd apps/web && pnpm start"
